// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package ebpf_probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type ebpf_counterFlowKey struct {
	Family uint8
	Proto  uint8
	Pad    uint16
	_      [4]byte
	Addrs  struct {
		Saddr   uint32
		Daddr   uint32
		SaddrHi uint64
		SaddrLo uint64
		DaddrHi uint64
		DaddrLo uint64
	}
	Sport uint16
	Dport uint16
	_     [4]byte
}

type ebpf_counterFlowStats struct {
	Packets   uint64
	Bytes     uint64
	FirstTsNs uint64
	LastTsNs  uint64
	Direction uint8
	Reserved  [7]uint8
}

type ebpf_counterIpInfo struct {
	FirstSeenTs uint64
	LastSeenTs  uint64
	PacketCount uint64
	ByteCount   uint64
}

type ebpf_counterIpKey struct {
	Prefixlen uint32
	Addr      uint32
}

type ebpf_counterSamplingConfig struct{ SampleRate uint32 }

// loadEbpf_counter returns the embedded CollectionSpec for ebpf_counter.
func loadEbpf_counter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Ebpf_counterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ebpf_counter: %w", err)
	}

	return spec, err
}

// loadEbpf_counterObjects loads ebpf_counter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ebpf_counterObjects
//	*ebpf_counterPrograms
//	*ebpf_counterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEbpf_counterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadEbpf_counter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ebpf_counterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpf_counterSpecs struct {
	ebpf_counterProgramSpecs
	ebpf_counterMapSpecs
	ebpf_counterVariableSpecs
}

// ebpf_counterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpf_counterProgramSpecs struct {
	DlTcProgramEntrypoint  *ebpf.ProgramSpec `ebpf:"dl_tc_program_entrypoint"`
	UlXdpProgramEntrypoint *ebpf.ProgramSpec `ebpf:"ul_xdp_program_entrypoint"`
}

// ebpf_counterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpf_counterMapSpecs struct {
	DebugFlags      *ebpf.MapSpec `ebpf:"debug_flags"`
	EventCounter    *ebpf.MapSpec `ebpf:"event_counter"`
	FlowStatistics  *ebpf.MapSpec `ebpf:"flow_statistics"`
	PacketEvents    *ebpf.MapSpec `ebpf:"packet_events"`
	SamplingControl *ebpf.MapSpec `ebpf:"sampling_control"`
	SamplingCounter *ebpf.MapSpec `ebpf:"sampling_counter"`
	UlSourceIps     *ebpf.MapSpec `ebpf:"ul_source_ips"`
}

// ebpf_counterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpf_counterVariableSpecs struct {
}

// ebpf_counterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEbpf_counterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpf_counterObjects struct {
	ebpf_counterPrograms
	ebpf_counterMaps
	ebpf_counterVariables
}

func (o *ebpf_counterObjects) Close() error {
	return _Ebpf_counterClose(
		&o.ebpf_counterPrograms,
		&o.ebpf_counterMaps,
	)
}

// ebpf_counterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEbpf_counterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpf_counterMaps struct {
	DebugFlags      *ebpf.Map `ebpf:"debug_flags"`
	EventCounter    *ebpf.Map `ebpf:"event_counter"`
	FlowStatistics  *ebpf.Map `ebpf:"flow_statistics"`
	PacketEvents    *ebpf.Map `ebpf:"packet_events"`
	SamplingControl *ebpf.Map `ebpf:"sampling_control"`
	SamplingCounter *ebpf.Map `ebpf:"sampling_counter"`
	UlSourceIps     *ebpf.Map `ebpf:"ul_source_ips"`
}

func (m *ebpf_counterMaps) Close() error {
	return _Ebpf_counterClose(
		m.DebugFlags,
		m.EventCounter,
		m.FlowStatistics,
		m.PacketEvents,
		m.SamplingControl,
		m.SamplingCounter,
		m.UlSourceIps,
	)
}

// ebpf_counterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadEbpf_counterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpf_counterVariables struct {
}

// ebpf_counterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEbpf_counterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpf_counterPrograms struct {
	DlTcProgramEntrypoint  *ebpf.Program `ebpf:"dl_tc_program_entrypoint"`
	UlXdpProgramEntrypoint *ebpf.Program `ebpf:"ul_xdp_program_entrypoint"`
}

func (p *ebpf_counterPrograms) Close() error {
	return _Ebpf_counterClose(
		p.DlTcProgramEntrypoint,
		p.UlXdpProgramEntrypoint,
	)
}

func _Ebpf_counterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ebpf_counter_bpfeb.o
var _Ebpf_counterBytes []byte
