// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package ebpf_probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type ebpf_counterFlowKey struct {
	Family uint8
	Proto  uint8
	Pad    uint16
	_      [4]byte
	Addrs  struct {
		Saddr   uint32
		Daddr   uint32
		SaddrHi uint64
		SaddrLo uint64
		DaddrHi uint64
		DaddrLo uint64
	}
	Sport uint16
	Dport uint16
	_     [4]byte
}

type ebpf_counterFlowStats struct {
	Packets   uint64
	Bytes     uint64
	FirstTsNs uint64
	LastTsNs  uint64
}

type ebpf_counterPktRing struct {
	Head  uint32
	Count uint32
	Recs  [16]struct {
		TsNs     uint64
		Len      uint32
		L4       uint8
		Dir      uint8
		TcpFlags uint8
		DscpEcn  uint8
	}
}

// loadEbpf_counter returns the embedded CollectionSpec for ebpf_counter.
func loadEbpf_counter() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Ebpf_counterBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ebpf_counter: %w", err)
	}

	return spec, err
}

// loadEbpf_counterObjects loads ebpf_counter and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ebpf_counterObjects
//	*ebpf_counterPrograms
//	*ebpf_counterMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEbpf_counterObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadEbpf_counter()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ebpf_counterSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpf_counterSpecs struct {
	ebpf_counterProgramSpecs
	ebpf_counterMapSpecs
	ebpf_counterVariableSpecs
}

// ebpf_counterProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpf_counterProgramSpecs struct {
	DlXdpProgramEntrypoint *ebpf.ProgramSpec `ebpf:"dl_xdp_program_entrypoint"`
	UlXdpProgramEntrypoint *ebpf.ProgramSpec `ebpf:"ul_xdp_program_entrypoint"`
}

// ebpf_counterMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpf_counterMapSpecs struct {
	FlowRecentPkts *ebpf.MapSpec `ebpf:"flow_recent_pkts"`
	FlowStatistics *ebpf.MapSpec `ebpf:"flow_statistics"`
}

// ebpf_counterVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ebpf_counterVariableSpecs struct {
}

// ebpf_counterObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEbpf_counterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpf_counterObjects struct {
	ebpf_counterPrograms
	ebpf_counterMaps
	ebpf_counterVariables
}

func (o *ebpf_counterObjects) Close() error {
	return _Ebpf_counterClose(
		&o.ebpf_counterPrograms,
		&o.ebpf_counterMaps,
	)
}

// ebpf_counterMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEbpf_counterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpf_counterMaps struct {
	FlowRecentPkts *ebpf.Map `ebpf:"flow_recent_pkts"`
	FlowStatistics *ebpf.Map `ebpf:"flow_statistics"`
}

func (m *ebpf_counterMaps) Close() error {
	return _Ebpf_counterClose(
		m.FlowRecentPkts,
		m.FlowStatistics,
	)
}

// ebpf_counterVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadEbpf_counterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpf_counterVariables struct {
}

// ebpf_counterPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEbpf_counterObjects or ebpf.CollectionSpec.LoadAndAssign.
type ebpf_counterPrograms struct {
	DlXdpProgramEntrypoint *ebpf.Program `ebpf:"dl_xdp_program_entrypoint"`
	UlXdpProgramEntrypoint *ebpf.Program `ebpf:"ul_xdp_program_entrypoint"`
}

func (p *ebpf_counterPrograms) Close() error {
	return _Ebpf_counterClose(
		p.DlXdpProgramEntrypoint,
		p.UlXdpProgramEntrypoint,
	)
}

func _Ebpf_counterClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ebpf_counter_bpfel.o
var _Ebpf_counterBytes []byte
